### ISSUE TITLE
[HELP] Decrypt payload need data

### ISSUE THREAD

**Issue by ndorigatti** [kormax/apple-vas#1]
Hello, 
i'm trying to follow this very useful guide to read and decrypt data from NFC Test Passes.

I'll generate my keys and have my passes in future, but for now I can only work on this public passes.

I have the private and public compressed keys, and i'm at the point of decrypting the payload but from the python example, some items are not clear to me:

`
PUBLIC_KEY_ASN_HEADER = bytearray.fromhex(
   "3039301306072a8648ce3d020106082a8648ce3d030107032200"
)

def generate_shared_info(pass_identifier: str):
    """
    :param pass_identifier: pass identifier
    :return: shared info used in X963 KDF when decrypting pass data
    """
    return bytes([
        *"ASN 1 RELATIVE-OID".encode("ascii"),
        *"REDACTED REDACTED REDACTED".encode("ascii"),
        *hashlib.sha256(pass_identifier.encode("ascii")).digest()
    ])
`

1. I'm wondering if PUBLIC_KEY_ASN_HEADER is always the same (or where i can find it, maybe from apple when i have my keys?)
2. What is "ASN 1 RELATIVE-OID" and/or where i can find it?
3. What do you mean for "REDACTED REDACTED REDACTED"

I'm quite comfortable with the rest of the code, i'm developing in java but it's quite easy, but I can't figure these three elements.

Can you please help me? 
Even in private, any help would be welcome!

Thank you

**Comment by kormax** [comment]
Hello. 

Public key header is the same. This constant is used to load device public key bytes into a library object in order to do ECDH. Your library might have a direct method for loading key bytes into an object, so you wouldn't need it.

Regarding the redacted/oid part:
If you re-read the document, decryption part in particular, it has all of the answers you need. I've redacted shared info generation on purpose and won't post it here directly. For it, visit the link in that section and read the document made by other person, it has the missing part.
