### ISSUE TITLE
[HELP] Automatic selection mode

### ISSUE THREAD

**Issue by daniel1pal419** [kormax/apple-vas#4]
Dear Kormax,
Thank you for these interesting information about Apple VAS.
I am curious about Apple VAS generic pass **automatic selection** mode.
I use Elatec's TWN4 MultiTech 3 NFC reader for Apple VAS and Google Smart Tap. However, when I present my own generic Apple VAS pass, the reader forces my default payment card instead of my pass. Does this the reader's incompatibility or my pass could be faulty. Btw, if I select the pass, then everything works as expected.
BR,
Daniel Pal

**Comment by kormax** [comment]
I would ask you to record a short video of the current behavior (need to see reader and what is happening on your screen), so that I would be able to understand the issue faster.

**Comment by daniel1pal419** [comment]
On Friday I will get back home, and I will be able to record it.

**Comment by renesass** [comment]
It's normal behavior that your phone is presenting your default payment card when putting near a NFC reader. However, that probably also means that the relevant pass could not be found/associated.

**Comment by daniel1pal419** [comment]
I reached the NFC reader manufacturer (Elatec RFID), they said that my NFC reader has Legic frontend IC, which has an older firmware that unfortunately does not support automatic pass selection, and I should buy an NXP version of the reader.

**Comment by kormax** [comment]
Oh, in that case, the previous commenter is right. I assumed from the initial message that reader was already configured for VAS + ECP, which is why I asked for a demo.

If a reader does not implement ECP, the device will in most cases ([apart from China](https://github.com/kormax/apple-device-as-access-card)) assume that it's a payment terminal, thus showing a default payment card for auth.
